const char page404[] PROGMEM =
"<head>\n"
"<style>\n"
"@import url('https://fonts.googleapis.com/css?family=Montserrat:400,600,700');\n"
"@import url('https://fonts.googleapis.com/css?family=Catamaran:400,800');\n"
".error-container {\n"
"  text-align: center;\n"
"  font-size: 180px;\n"
"  font-family: 'Catamaran', sans-serif;\n"
"  font-weight: 800;\n"
"  margin: 20px 15px;\n"
"}\n"
".error-container > span {\n"
"  display: inline-block;\n"
"  line-height: 0.7;\n"
"  position: relative;\n"
"  color: #FFB485;\n"
"}\n"
".error-container > span {\n"
"  display: inline-block;\n"
"  position: relative;\n"
"  vertical-align: middle;\n"
"}\n"
".error-container > span:nth-of-type(1) {\n"
"  color: #D1F2A5;\n"
"  animation: colordancing 4s infinite;\n"
"}\n"
".error-container > span:nth-of-type(3) {\n"
"  color: #F56991;\n"
"  animation: colordancing2 4s infinite;\n"
"}\n"
".error-container > span:nth-of-type(2) {\n"
"  width: 120px;\n"
"  height: 120px;\n"
"  border-radius: 999px;\n"
"}\n"
".error-container > span:nth-of-type(2):before,\n"
".error-container > span:nth-of-type(2):after {\n"
"\tborder-radius: 0%;\n"
"\tcontent:\"\";\n"
"\tposition: absolute;\n"
"\ttop: 0; left: 0;\n"
"\twidth: inherit; height: inherit;\n"
"  border-radius: 999px;\n"
"\tbox-shadow: inset 30px 0 0 rgba(209, 242, 165, 0.4),\n"
"\t\t\t\tinset 0 30px 0 rgba(239, 250, 180, 0.4),\n"
"\t\t\t\tinset -30px 0 0 rgba(255, 196, 140, 0.4),\t\n"
"\t\t\t\tinset 0 -30px 0 rgba(245, 105, 145, 0.4);\n"
"  animation: shadowsdancing 4s infinite;\n"
"}\n"
".error-container > span:nth-of-type(2):before {\n"
"\t-webkit-transform: rotate(45deg);\n"
"\t   -moz-transform: rotate(45deg);\n"
"\t\t\ttransform: rotate(45deg);\n"
"}\n"
"\n"
".screen-reader-text {\n"
"    position: absolute;\n"
"    top: -9999em;\n"
"    left: -9999em;\n"
"}\n"
"@keyframes shadowsdancing {\n"
"  0% {\n"
"    box-shadow: inset 30px 0 0 rgba(209, 242, 165, 0.4),\n"
"\t\t\t\tinset 0 30px 0 rgba(239, 250, 180, 0.4),\n"
"\t\t\t\tinset -30px 0 0 rgba(255, 196, 140, 0.4),\t\n"
"\t\t\t\tinset 0 -30px 0 rgba(245, 105, 145, 0.4);\n"
"  }\n"
"  25% {\n"
"    box-shadow: inset 30px 0 0 rgba(245, 105, 145, 0.4),\n"
"\t\t\t\tinset 0 30px 0 rgba(209, 242, 165, 0.4),\n"
"\t\t\t\tinset -30px 0 0 rgba(239, 250, 180, 0.4),\t\n"
"\t\t\t\tinset 0 -30px 0 rgba(255, 196, 140, 0.4);\n"
"  }\n"
"  50% {\n"
"     box-shadow: inset 30px 0 0 rgba(255, 196, 140, 0.4),\n"
"\t\t\t\tinset 0 30px 0 rgba(245, 105, 145, 0.4),\n"
"\t\t\t\tinset -30px 0 0 rgba(209, 242, 165, 0.4),\t\n"
"\t\t\t\tinset 0 -30px 0 rgba(239, 250, 180, 0.4);\n"
"  }\n"
"  75% {\n"
"   box-shadow: inset 30px 0 0 rgba(239, 250, 180, 0.4),\n"
"\t\t\t\tinset 0 30px 0 rgba(255, 196, 140, 0.4),\n"
"\t\t\t\tinset -30px 0 0 rgba(245, 105, 145, 0.4),\t\n"
"\t\t\t\tinset 0 -30px 0 rgba(209, 242, 165, 0.4);\n"
"  }\n"
"  100% {\n"
"    box-shadow: inset 30px 0 0 rgba(209, 242, 165, 0.4),\n"
"\t\t\t\tinset 0 30px 0 rgba(239, 250, 180, 0.4),\n"
"\t\t\t\tinset -30px 0 0 rgba(255, 196, 140, 0.4),\t\n"
"\t\t\t\tinset 0 -30px 0 rgba(245, 105, 145, 0.4);\n"
"  }\n"
"}\n"
"@keyframes colordancing {\n"
"  0% {\n"
"    color: #D1F2A5;\n"
"  }\n"
"  25% {\n"
"    color: #F56991;\n"
"  }\n"
"  50% {\n"
"    color: #FFC48C;\n"
"  }\n"
"  75% {\n"
"    color: #EFFAB4;\n"
"  }\n"
"  100% {\n"
"    color: #D1F2A5;\n"
"  }\n"
"}\n"
"@keyframes colordancing2 {\n"
"  0% {\n"
"    color: #FFC48C;\n"
"  }\n"
"  25% {\n"
"    color: #EFFAB4;\n"
"  }\n"
"  50% {\n"
"    color: #D1F2A5;\n"
"  }\n"
"  75% {\n"
"    color: #F56991;\n"
"  }\n"
"  100% {\n"
"    color: #FFC48C;\n"
"  }\n"
"}\n"
"\n"
"/* demo stuff */\n"
"* {\n"
"    -webkit-box-sizing: border-box;\n"
"    -moz-box-sizing: border-box;\n"
"    box-sizing: border-box;\n"
"}\n"
"body {\n"
"  background-color: #416475;\n"
"  margin-bottom: 50px;\n"
"}\n"
"html, button, input, select, textarea {\n"
"    font-family: 'Montserrat', Helvetica, sans-serif;\n"
"    color: #92a4ad;\n"
"}\n"
"h1 {\n"
"  text-align: center;\n"
"  margin: 30px 15px;\n"
"}\n"
".zoom-area { \n"
"  max-width: 490px;\n"
"  margin: 30px auto 30px;\n"
"  font-size: 19px;\n"
"  text-align: center;\n"
"}\n"
".link-container {\n"
"  text-align: center;\n"
"}\n"
"a.more-link {\n"
"  text-transform: uppercase;\n"
"  font-size: 13px;\n"
"    background-color: #92a4ad;\n"
"    padding: 10px 15px;\n"
"    border-radius: 0;\n"
"    color: #416475;\n"
"    display: inline-block;\n"
"    margin-right: 5px;\n"
"    margin-bottom: 5px;\n"
"    line-height: 1.5;\n"
"    text-decoration: none;\n"
"  margin-top: 50px;\n"
"  letter-spacing: 1px;\n"
"}\n"
"   </style>\n"
"</head> \n"
"\n"
"<h1>404 Not Found This Page</h1>\n"
"<p class=\"zoom-area\"> Comeback Soooooooon </p>\n"
"<section class=\"error-container\">\n"
"  <span>4</span>\n"
"  <span><span class=\"screen-reader-text\">0</span></span>\n"
"  <span>4</span>\n"
"</section>\n"
"<div class=\"link-container\">\n"
"  <a target=\"_blank\" href=\"https://www.facebook.com/chaudo1910\" class=\"more-link\">Contact Me</a>\n"
"</div>"
;

const char pageWifiA[] PROGMEM = 
"<html>\n"
"<style>\n"
"body {\n"
"    text-align: center;\n"
"}\n"
"h1 {\n"
"    color: green;\n"
"    font-family: Sans-serif;\n"
"}\n"
"p1 {\n"
"\ttext-align: left;\n"
"    color: green;\n"
"    font-family: Sans-serif;\n"
"    text-align: center;\n"
"}\n"
"input[type=text], select {\n"
"  width: 50%;\n"
"  padding: 12px 20px;\n"
"  margin: 8px 0;\n"
"  display: inline-block;\n"
"  border: 1px solid #ccc;\n"
"  border-radius: 4px;\n"
"  box-sizing: border-box;\n"
"}\n"
"input[type=password], select {\n"
"  width: 50%;\n"
"  padding: 12px 20px;\n"
"  margin: 8px 0;\n"
"  display: inline-block;\n"
"  border: 1px solid #ccc;\n"
"  border-radius: 4px;\n"
"  box-sizing: border-box;\n"
"  -webkit-transition: width 0.4s ease-in-out;\n"
"  transition: width 0.4s ease-in-out;\n"
"  \n"
"}\n"
"input[type=submit] {\n"
"  width: 50%;\n"
"  background-color: #4CAF50;\n"
"  color: white;\n"
"  padding: 14px 20px;\n"
"  margin: 8px 0;\n"
"  border: none;\n"
"  border-radius: 4px;\n"
"  cursor: pointer;\n"
"}\n"
"\n"
"input[type=submit]:hover {\n"
"  background-color: #45a049;\n"
"}\n"
"\n"
"div {\n"
"  border-radius: 5px;\n"
"  background-color: #f2f2f2;\n"
"  padding: 20px;\n"
"}\n"
"</style>\n"
"<body>\n"
"<h1> SENSOR Device Configuration </h1>\n"
"<p1>SSID</p1>\n"
"<br>"
"<select name=\"ssid\" form=\"wifi\">"
;

const char pageWifiB[] PROGMEM =
"</select>\n"
"<form action=\"/wificf\" id=\"wifi\">\n"
"  <p1>Password</p1><br>\n"
"  <input type=\"password\" name=\"pass\">\n"
"  <br>\n"
"  \n"
"  <input type=\"submit\" value=\"OK\">\n"
"</form>\n"
"</body>\n"
"</html>\n"
;
//const char pageRestart[] PROGMEM =
//"\
//</select>\
//<form action=\"/cf\" method=\"get\" target=\"\">\
//  WIFI SSID : <input type=\"text\" name=\"ssid\"><br>\
//  PASSWORD : <input type=\"password\" name=\"pass\"><br>\
//  <button type=\"submit\">Submit</button>\
//</form>\
//";

const char pageRestart[] PROGMEM =
"<html>\n"
"<head>\n"
"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
"<style>\n"
"body {\n"
"    text-align: center;\n"
"}\n"
"h1 {\n"
"    color: green;\n"
"    font-family: Sans-serif;\n"
"}\n"
"p {\n"
"  color: white;\n"
"  text-align: center;\n"
"  font-family: Arial, Helvetica, sans-serif;\n"
"  background-color: red;\n"
"  width: 50%;\n"
"  border-radius: 4px;\n"
"  padding: 14px 20px;\n"
"  margin: 25%;\n"
"\n"
"}\n"
"</style>\n"
"</head>\n"
"<body>\n"
"<br>"
"<br>"
"<br>"
"<br>"
"<br>"
"<br>"
"<br>"
"<br>"
"<br>"
"<br>"
"<br>"
"<p id=\"demo\">Connecting and restarting in 20</p>\n"
"\n"
"<script>\n"
"var secs = 20;\n"
"var x = setInterval(function() {\n"
"  secs = secs - 1 ;\n"
"  document.getElementById(\"demo\").innerHTML =  \"Connecting and restarting in \"+ secs;\n"
"  if (secs < 0) {\n"
"    clearInterval(x);\n"
"    document.getElementById(\"demo\").innerHTML = \"Restarting...\";\n"
"  }\n"
"}, 1000);\n"
"setTimeout(function(){\n"
"            window.location.href = 'http://google.vn';\n"
"         }, 20000);\n"
"</script>\n"
"</body>\n"
"</html>\n"
"";

String pagemqttCf =""
"<html>\n"
"<style>\n"
"body {\n"
"    text-align: center;\n"
"}\n"
"h1 {\n"
"    color: green;\n"
"    font-family: Sans-serif;\n"
"}\n"
"p1 {\n"
"\ttext-align: left;\n"
"    color: green;\n"
"    font-family: Sans-serif;\n"
"    text-align: center;\n"
"}\n"
"p2 {\n"
"\ttext-align: left;\n"
"    color: gray;\n"
"    font-family: Sans-serif;\n"
"    text-align: center;\n"
"}\n"
"p3 {\n"
"\ttext-align: left;\n"
"    color: red;\n"
"    font-family: Sans-serif;\n"
"    text-align: center;\n"
"}\n"
"input[type=text], select {\n"
"  width: 50%;\n"
"  padding: 12px 20px;\n"
"  display: inline-block;\n"
"  border: 1px solid #ccc;\n"
"  border-radius: 4px;\n"
"  box-sizing: border-box;\n"
"}\n"
"input[type=password], select {\n"
"  width: 50%;\n"
"  padding: 12px 20px;\n"
"  display: inline-block;\n"
"  border: 1px solid #ccc;\n"
"  border-radius: 4px;\n"
"  box-sizing: border-box;\n"
"  -webkit-transition: width 0.4s ease-in-out;\n"
"  transition: width 0.4s ease-in-out;\n"
"  \n"
"}\n"
"input[type=submit] {\n"
"  width: 50%;\n"
"  background-color: #4CAF50;\n"
"  color: white;\n"
"  padding: 14px 20px;\n"
"  margin: 8px 0;\n"
"  border: none;\n"
"  border-radius: 4px;\n"
"  cursor: pointer;\n"
"  margin: auto;\n"
"}\n"
"\n"
"input[type=submit]:hover {\n"
"  background-color: #45a049;\n"
"}\n"
"\n"
"div {\n"
"  border-radius: 5px;\n"
"  background-color: #f2f2f2;\n"
"  padding: 20px;\n"
"}\n"
"</style>\n"
"<body>\n"
"<h1> <center>SENSOR MQTT Configuration </center> </h1>\n"
"<form action=\"/mqttcf\" id=\"mqtt\">\n"
"  <p1> MQTT Host     </p1>\n"
"  <br>\n"
"  <input type=\"text\" name=\"host\"  value=\"hostvalue\">\n"
"  <br>\n"
"  <p1> MQTT Port     </p1>\n"
"  <br>\n"
"  <input type=\"text\" name=\"port\"  value=\"portvalue\">\n"
"  <br>\n"
"  <p3> MQTT Username </p3>\n"
"  <br>\n"
"  <input type=\"text\" name=\"user\"  value=\"uservalue\">\n"
"  <br>\n"
"  <p3> MQTT Password </p3>\n"
"  <br>\n"
"  <input type=\"text\" name=\"pass\"  value=\"passvalue\">\n"
"  <br>\n"
"  <p2> MQTT Status Topic (%%ID%%= deviceID)</p2>\n"
"  <br>\n"
"  <input type=\"text\" name=\"stat\"  value=\"statusvalue\">\n"
"  <br>\n"
"  <p2> MQTT Command Topic (%%ID%%= deviceID)</p2>\n"
"  <br>\n"
"  <input type=\"text\" name=\"cmnd\"  value=\"cmdvalue\">\n"
"  <br>\n"
"  <p2> MQTT Result Topic (%%ID%%= deviceID)</p2>\n"
"  <br>\n"
"  <input type=\"text\" name=\"rest\"  value=\"resultvalue\">\n"
"  <br>\n"
"  <br>\n"
"  <input type=\"submit\" value=\"OK\">\n"
"</form>\n"
"</body>\n"
"</html>";

const char pageMain[] PROGMEM =
"\
";

const char pageSimCMD[] PROGMEM =
"\
";
